---
- name: Clone Lets Encrypt | git
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: /src/lets-encrypt

- name: request signed certificate
  shell: "/src/letsencrypt-auto certonly --standalone -d {{ role }}.{{ project }}-{{ environment_tier }}.{{ domain }}"