---
- name: Clone Lets Encrypt | git
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: /src/lets-encrypt

- name: request signed certificate
  sudo: no
  shell: "/src/lets-encrypt/letsencrypt-auto certonly --standalone{% if letsencrypt_agree_tos %} --agree-tos {% endif %} {% if letsencrypt_email %} --email {{ letsencrypt_email }} {% endif %} -d {{ letsencrypt_domain }}"
