---
- name: Clone Lets Encrypt | git
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: "{{ letsencrypt_source }}"

# - name: request signed certificate
#   sudo: no
#   shell: "{{ letsencrypt_source }}/letsencrypt-auto certonly --standalone{% if letsencrypt_agree_tos %} --agree-tos {% endif %} {% if letsencrypt_email %} --email {{ letsencrypt_email }} {% endif %} -d {{ letsencrypt_domain }}"

- name: create /data/www if does not exist
  file:
    path: "{{ letsencrypt_path }}"
    state: directory
    owner: "{{ letsencrypt_owner }}"
    group: "{{ letsencrypt_group }}"
    mode: 0755

- name: read in public data
  shell: "cat /etc/letsencrypt/live/{{ letsencrypt_domain }}/fullchain.pem"
  register: letsencrypt_public_key.stdout

- name: read in private key data
  shell: "cat /etc/letsencrypt/live/{{ letsencrypt_domain }}/privkey.pem"
  register: letsencrypt_private_key.stdout

- name: write combined ssl file
  template:
    src: data/www/ssl.combined
    dest: "{{ letsencrypt_path_combined }}"
    owner: "{{ letsencrypt_owner }}"
    group: "{{ letsencrypt_group }}"
    mode: 0440
